config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:delete, :get]


  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"
  get "/users/:id", to: "pages#profile"

  resources :swap_request
  resources :tontines do
    member do
      get :list_users_from_company
      get :add_users_to_tontine
      get :accepte_member
      get :decline_member
      get :chatroom
    end
   resources :messages, only: :create
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tontine.rb
class Tontine < ApplicationRecord
  belongs_to :user
  has_many :messages
  has_many :members, -> { order(position: :asc) }, dependent: :destroy
  has_many :users, -> { order("members.position ASC") }, through: :members
  has_one_attached :cover
  
  STATUS_TRANSLATIONS = {
    pending: "En attente",
    active: "En cours",
    done: "Terminée"
  }.freeze

  STATUS = STATUS_TRANSLATIONS.keys.map(&:to_s).freeze

  validates :status, inclusion: { in: Tontine::STATUS }

  after_create :create_first_member

  def current_position
    Date.today.month - self.start_month.month + 1
  end

  def status_fr
    STATUS_TRANSLATIONS[status.to_sym]
  end

  private

  def create_first_member
    Member.create(user: self.user, tontine: self, status: "confirmed", position: 1)
  end
end

app/controllers/tontines_controller.rb
class TontinesController < ApplicationController
  before_action :set_tontine, only: %i[edit show destroy update chatroom]

  def index
    @tontines = Tontine.all
  end

  def show
    @is_owner = @tontine.user.id == current_user.id
    @message = Message.new
  end

  def new
    @tontine = Tontine.new
  end

  def create
    @tontine = Tontine.new(params_tontine)
    @tontine.user = current_user
    @tontine.status = "pending"
    @tontine.participants = params[:tontine][:user_ids].size
    params[:tontine][:user_ids].each do |user_id|
      Member.create(
        user_id: user_id.to_i,
        tontine: @tontine,
        position: @tontine.members.count + 2,
        status: "pending"
      )
    end

    if @tontine.save!
      redirect_to tontine_path(@tontine)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @tontine.update(params_tontine)
    redirect_to tontine_path(@tontine)
  end

  def destroy
    @tontine.update(params_tontine)
    redirect_to tontines_path, status: :see_other
  end

  def list_users_from_company
    @tontine = Tontine.find(params[:id])
    @users_to_add = User.where(company: current_user.company)
  end

  def add_users_to_tontine
    @tontine = Tontine.find(params[:id])
    @users_to_add = User.where(company: current_user.company)

    @users_to_add.each_with_index do |user, index|
      member = Member.new(
        user: user,
        tontine: @tontine,
        position: index + 1,
        status: "pending"
      )
      member.status = "accepted" if user.id == current_user.id
      member.save!
    end

    redirect_to tontine_path(@tontine)
  end

  def accepte_member
    @tontine = Tontine.find(params[:id])
    current_user.members.where(tontine: @tontine).first.update(status: "accepted")
    redirect_to tontine_path(@tontine)
  end

  def decline_member
    @tontine = Tontine.find(params[:id])
    current_user.members.where(tontine: @tontine).first.update(status: "declined")
    redirect_to dashboard_path
  end

  def chatroom
    @message = Message.new
    session[:messages_counter] = nil
  end

  private

  def set_tontine
    @tontine = Tontine.find(params[:id])
  end

  def params_tontine
    params.require(:tontine).permit(:name, :contribution, :start_month, :payment_day,
      :participants).tap do |params|
      params[:start_month] = DateTime.parse(params[:start_month] + "/01")
    end
  end
end

app/views/tontines/_day_label.html.erb
<div class="day-label">
  le <span><%= day.first %></span>
</div>

app/views/tontines/_form_avatar.html.erb
<div class="d-flex align-items-center justify-content-center flex-column text-center">
  <%= cl_image_tag member.photo.key, class:"avatar-form" %>
  <span><%= member.first_name.strip %></span>
</div>

<style>
.avatar-form {
  border-radius: 50%;
  width: 50px;
  height: 50px;
  object-fit: cover;
  object-position: center;
}

</style>

app/views/tontines/_message.html.erb
    <% sender = message.user == current_user %>
  <div id="message-<%= message.id %> <%= 'sender' if sender %>">
      <div class="message-content">
      <%= cl_image_tag message.user.photo.key, class:"avatar-chatroom"%>
      <strong><%= message.user.first_name %></strong>
      <i><%= message.created_at.strftime("%H:%M") %></i>
      </div>
     <p><%= message.body %></p>
  </div>  

app/views/tontines/_show_admin.html.erb
<div>
  <h1 class="tontine_title">  </h1>
</div>

app/views/tontines/_tontine_card.html.erb
<%= link_to tontine_path(tontine) do %>
  <div class="tontine-card">
  	<div class="tontine-card__header">
  		<div class="tontine-card__header__name">
  			<%= tontine.name %>
  		</div>
  		<div class="tontine-card__header__contribution">
  			<%= tontine.contribution %>€<span>/mois</span>
  		</div>
  	</div>
  	<div class="tontine-card__avatars">
  		<% tontine.members.each do |member| %>
  			<%= cl_image_tag(member.user.photo.key, width: 200, class: "avatar-large #{'past-position' if member.position < tontine.current_position} #{'current-position' if member.position == tontine.current_position}") %>
  		<% end %>
  	</div>
  </div>
<% end -%>

app/views/tontines/add_members.html.erb
<link rel="stylesheet" type="text/css" href="_form.css">

<div class ="form_style">
  <form action="/tontines/<%= @tontine.id %>/add_members" method="patch">
  <% (1...@tontine.participants).map do |i| %>
   <select name="member<%=i%>">
   <% @users.each do |user| %>
    <option value="<%= user.id %>"><%= "#{user.first_name} #{user.last_name}" %></option>
    <% end %>
  </select>
  <% end %>
  <input type="submit" value="Add Members">
</div>

app/views/tontines/chatroom.html.erb
<% content_for(:navigation) do %>
  <%= link_to tontine_path(@tontine), class: 'nav-link' do %>
    <i class="fa-solid fa-backward"></i>
  <% end -%>
<% end -%>

<div class="container chatroom-container"
  data-controller="tontine-subscription"
  data-tontine-subscription-tontine-id-value="<%= @tontine.id %>"
  data-tontine-subscription-user-id-value="<%= current_user.id %>">
  <div class="tontine-show__header mb-2 text-center">
    <h1 class="text-center"><%= @tontine.name %> - <%= number_with_delimiter(@tontine.contribution * @tontine.members.count, delimiter: " ") %>€</h1>
    <div class="badge-status mb-2"><%= @tontine.status_fr %></div>
  </div>
  <div class="messages mb-2" data-tontine-subscription-target="messages">
    <% @tontine.messages.each do |message| %>
      <%= render "messages/message", message: message %>
    <% end %>
  </div>
  <%= simple_form_for [@tontine, @message],
    html: {data: {
      action: "turbo:submit-end->tontine-subscription#resetForm"
    },
    class: "message-form d-flex mb-3"} do |f| %>
    <%= f.input :body,
      label: false,
      placeholder: "Ecrivez votre message au membre",
      wrapper_html: {class: "flex-grow-1 mb-0"} %>
    <%= button_tag type: 'submit' do %>
      <i class="fa-solid fa-paper-plane"></i>
    <% end %>
 <% end %>
</div>

app/views/tontines/edit.html.erb
<ul class="list-group list-group-numbered">
  <li class="list-group-item d-flex justify-content-between align-items-start">
    <div class="ms-2 me-auto">
      <div class="fw-bold">Subheading</div>
      Cras justo odio
    </div>
    <span class="badge bg-success rounded-pill">Accepté</span>
  </li>
</ul>

app/views/tontines/index.html.erb
<h1>Tontineo</h1>
<h3>Créer votre tontine et inviter vos collègues !</h3>
<% @tontines.each do |tontine| %>
  <%= link_to tontine.name, tontine_path(tontine) %>
<% end %>

app/views/tontines/list_users_from_company.html.erb
<div class="container">
  <% @users_to_add.each do |user| %>
    <p><%= user.first_name %></p>
  <% end  %>
</div>

<%= link_to "Ajouter ces utilisateurs", add_users_to_tontine_tontine_path(@tontine) %>

app/views/tontines/new.html.erb
<div class="my-5 mx-3" >
  <h2 class="text-center m-3">Nouvelle tontine</h2>
  <div class ="form_style" data-controller="flatpickr">
    <%= simple_form_for @tontine, html: { data: { turbo: false }} do |f| %>
      <%= f.input :name,label: 'Nom', placeholder: "Comment s'appelle votre tontine ?" %>
      <%= f.input :contribution,label: 'Contribution ', placeholder: 'Montant à verser' %>
      <%= f.input :start_month,
        as: :string,
        label: 'Mois de départ',
        placeholder: 'Début de la tontine !',
        input_html:{
          data: { flatpickr_target: 'monthPickr' }
        } %>
      <%#= f.input :cover, as: :file %>
      <%= f.input :payment_day,
        label: 'Jour de paiement',
        as: :radio_buttons,
        placeholder: 'Jour du paiement',
        collection: [["1er", 1], ["10", 10], ["20", 20], ["25", 25]],
        wrapper_html: {class: 'd-flex'},
        include_blank: false,
        include_hidden: false,
        wrapper_tag: :div,
        wrapper_class: 'days-container mb-3',
        label_method: lambda { |day| render 'tontines/day_label', day: day } %>
      <!-- <h2>Sélectionner des participants :</h2> -->
      <%= f.association :users,
        label: 'Sélectionner des participants',
        as: :check_boxes,
        collection: User.all.where.not(id: current_user.id),
        # wrapper_html: {class: 'd-flex'},
        include_blank: false,
        include_hidden: false,
        input_html: {class: 'category-selector mb-3'},
        label_method: lambda { |member| render 'tontines/form_avatar', member: member } %>
      <%#= f.input :participants,label: 'Participants', placeholder: "Nombre de participants !"%>
      <%# <%= f.input :users,label: 'Utilisateurs', placeholder: "Mail du participant !" %>
      <%# <%= f.input :image, label: 'Ta photo', placeholder: 'Envoie une photo' %>
      <%# <div class="mb-3 string optional basket_photo"> %>
      <%# <label class="form-label string optional" for="basket_price_per_day">Ta photo</label>
      <input class="form-control string optional" placeholder="Envoie une photo" type="text" name="image"></div> %>
      <%= f.submit "Valider", class:"btn-rounded btn purple-btn py-3 w-100 text-white"%>
      <%# <i class="fa-solid fa-basketball"></i> %>
    <% end %>
  </div>
</div>

app/views/tontines/show.html.erb
<% content_for(:navigation) do %>
  <%= link_to dashboard_path, class: 'nav-link' do %>
    <i class="fa-solid fa-backward"></i>
  <% end -%>
<% end -%>

<div class="container">
  <div class="tontine-show__header mb-4 text-center">
    <h1 class="text-center"><%= @tontine.name %> - <%= number_with_delimiter(@tontine.contribution * @tontine.members.count, delimiter: " ") %>€</h1>
    <div class="badge-status mb-2"><%= @tontine.status_fr %></div>
    <div class="tontine-show__header__chatroom">
      <% if request.referer&.include?("dashboard") %>
        <div class="counter">2</div>
      <% end -%>
      <%= link_to chatroom_tontine_path(@tontine), class: 'btn-rounded btn purple-btn' do %>
        <i class="fa-solid fa-comments"></i>
        <span>Discussion</span>
      <% end -%>
    </div>
  </div>
  <h4 class="underline mt-3 mb-2 text-center">Infos</h4>
  <div class="tontine-show__infos">
    <!-- <div>
      <div class="label">Nombre de participants :</div>
      <div class="value"><%#= @tontine.members.count %></div>
    </div> -->
<!--     <div>
      <div class="label">Montant Total :</div>
      <div class="value color-purple"><%= number_with_delimiter(@tontine.contribution * @tontine.members.count, delimiter: " ") %>€</div>
    </div> -->
    <div>
      <div class="label">Versement mensuel :</div>
      <div class="value"><%= @tontine.contribution %>€<span>/mois</span></div>
    </div>
    <div>
      <div class="label">Date de versement :</div>
      <div class="value">le <%= @tontine.payment_day %><%= "er" if @tontine.payment_day == 1 %> du mois</div>
    </div>
    <div>
      <div class="label">Début :</div>
      <div class="value"><%= I18n.l(@tontine.start_month, format: "%B %Y") %></div>
    </div>
    <div>
      <div class="label">Fin :</div>
      <div class="value"><%= I18n.l(@tontine.start_month + @tontine.members.count.month, format: "%B %Y") %></div>
    </div>
  </div>
  <h4 class="underline mt-3 mb-2 text-center">Calendrier</h4>
  <div class="members_list">
    <% @tontine.members.each do |member| %>
      <div class="card-planning <%= 'past-position' if member.position < @tontine.current_position %> <%= 'current-position' if member.position == @tontine.current_position%> ">
        <strong><%= I18n.l(@tontine.start_month + (member.position - 1).month, format: "%B %Y") %></strong>
        <div class="card-planning__user">
          <span><%= member.user.first_name %></span>
          <%= cl_image_tag(member.user.photo.key, width: 200, class: "avatar-large") %>
        </div>
      </div>
    <% end %>
  </div>
</div>