config/routes.rb
Rails.application.routes.draw do
  devise_for :users, sign_out_via: [:delete, :get]


  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"
  get "/users/:id", to: "pages#profile"

  resources :swap_request
  resources :tontines do
    member do
      get :list_users_from_company
      get :add_users_to_tontine
      get :accepte_member
      get :decline_member
      get :chatroom
    end
   resources :messages, only: :create
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<div class="footer stickyFooter ">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Codé by <i class="fas fa-heart" style="font-size: 20px;margin-bottom: 0px; margin-top: 0px;"></i> par <a href="https://twitter.com/jrkinouani" target="blank">Jrkinouani and co</a>
  </div>
</div>


<!--<div class="footer">
  <%#= link_to dashboard_path, class: 'footer-nav' do %>
    <i class="fa-solid fa-list-check"></i>
    <span>Tontines</span>
  <#% end %>
  <#%= link_to "#", class: 'footer-nav' do %>
    <i class="fa-solid fa-bell"></i>
    <span>Notifications</span>
  <%# end -%>
  <%#= link_to "#", class: 'footer-nav footer-chatrooms' do %>
    <i class="fa-solid fa-comments">
      <%# if session[:messages_counter].present? %>
        <div class="counter"><%= session[:messages_counter] %></div>
      <%# end -%>
    </i>
    <span>Discussions</span>
  <%# end -%>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <% if user_signed_in? %>
     <%= link_to dashboard_path, class: 'home-link' do %>
       <div class="logo-wrapper d-flex justify-content-start">
        <%= image_tag "img/apple-icon.png", class: 'logo-home' %>
        <p class="home-title">Tontineo</p>
       </div>
      <% end %>
    <% else %>
        <div class="logo-wrapper d-flex justify-content-start">
          <%= image_tag "img/apple-icon.png", class: 'logo-home' %>
          <p class="home-title">Tontineo</p>
        </div>
    <% end %>
     <%#= image_tag "img/apple-icon.png", class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
         <% if user_signed_in? %>
         <li class="nav-item active">
            
          </li>
          <li class="nav-item">
             <%#= link_to  "Dashboard", dashboard_path, class: 'nav-link' %>
          </li>
          <li class="nav-item active">
            
          </li>
          <li class="nav-item">
          <%#= link_to "Sign out", destroy_user_session_path, :method => :delete %>
          </li>
          <li class="nav-item dropdown">
            <!--<img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />-->
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
            </div>
          </li>
          <%= link_to "Créer une tontine", new_tontine_path, class:"btn-rounded btn purple-btn py-3" %>
          <% else %>
         <li class="nav-item active">
            <a class="nav-link" href="#">Comment ça marche ?</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="#">Tarifs</a>
          </li>
            <li class="nav-item">
            <%= link_to "Se connecter", new_user_session_path, class:"text-center" unless user_signed_in? %>
            </li>
          <% end %>
      </ul>
    </div>
  </div>
</div>






<!-- <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid navbar">
    <%# if user_signed_in? %>
      <div>
        <%#= yield(:navigation) if content_for?(:navigation) %>
      </div>
      <%#= link_to current_page?(dashboard_path) ? root_path : dashboard_path, class: 'home-link' do %>
        <div class="logo-wrapper d-flex justify-content-center">
          <%#= image_tag "img/apple-icon.png", class: 'logo-home' %>
        </div>
      <%# end %>
      <%#= link_to destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link log-out" do %>
        <i class="fa-solid fa-right-from-bracket"></i>
      <%# end -%>
    <%# else %>
      <%#= link_to root_path do %>
        <div class="logo-wrapper d-flex justify-content-center">
          <%#= image_tag "img/apple-icon.png", class: 'logo-home' %>
        </div>
      <%# end -%>
    <%# end %>
    </div>
  </div>
</div>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%  
  meta_title = "Tontineo - Réveillez votre argent par le prêt entre collègues" 
  meta_description = "Tontineo est une plateforme de prêt entre collègues qui vous permet de réveiller votre argent en le prêtant à vos collègues." 
  meta_image = image_tag("img/og_image.png").split('"')[1]
  meta_twitter_site = "@tontineo"
%>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= meta_twitter_site %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= meta_twitter_site %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= render 'shared/ios_pwa_links' %>
  </head>
  <body>
     <%= render 'layouts/navbar' %>
     <%= yield %>
     <%= render 'layouts/footer' %>
  </body>

  <!-- <body id="<%= controller_name %>_<%= action_name %>">
    <%#= render 'layouts/navbar' unless current_page?(root_path) %>
    <div class="<%= current_page?(root_path) ? 'h-100' : 'page-content' %>">
      <%#= yield %>
    </div>
    <%#= render 'layouts/footer' if action_name != 'home' && user_signed_in? %>
  </body> -->
</html>